name: Make Terraform configurations for all AWS regions
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  make:
    name: make regions.tf.json
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sh regions.sh > regions.tf.json
      - uses: stefanzweifel/git-auto-commit-action@v4
